server:
  port: 8080

spring:
  application:
    name: twittarep-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:twittarep_backend}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

app:
  security:
    audience: ${AUTH0_AUDIENCE}
  cors:
    allowed-origins:
      - ${FRONTEND_LOCAL_ORIGIN}
      - ${FRONTEND_S3_ORIGIN}
